<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BeerTableSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        DB::table('beers')->insert([
            [
                'id' => 1,
                'brewer' => "Dad & Dave's Brewing",
                'name' => "BOBA BEER",
                'description' => "A delightfully tart Grapefruit Beliner Weisse infused with Jasmine Green Tea. Bit notes of citrus and floral jasmine. Serve with Tapioca Pearls for full experience!",
                'style' => "Sour - Berliner Weisse",
                'abv' => 6.0,
                'complexity' => "STEPPING UP",
                'section_id' => 1,
            ],
            [
                'id' => 2,
                'brewer' => "The Coastal Brewing Company",
                'name' => "HOMESTEAD BLACKBERRY & APPLE PASTRY SOUR",
                'description' => "Perfect for an autumn or winter evening bringing crumble to a glass!",
                'style' => "Specialty Beer",
                'abv' => 6.0,
                'complexity' => "EASY DRINKING",
                'section_id' => 1,
            ],
            [
                'id' => 3,
                'brewer' => "7th Day Brewery",
                'name' => "SUIT UP",
                'description' => "A dark malt base gives off a roasted flavours. Chocolate and raisins mingle with piney resin and citric floral hops. Suit up and enjoy the ride!",
                'style' => "IPA - Black",
                'abv' => 6.5,
                'complexity' => "STEPPING UP",
                'section_id' => 1,
            ],
            [
                'id' => 4,
                'brewer' => "Six String Brewing Co.",
                'name' => "WHISKEY IN THE JAR",
                'description' => "A barrel aged, American-Style Imperial Stout. Conditioned on a single batch whiskey distilled from a stout inspired wash. This beer is a \"Boilermaker\" in a glass",
                'style' => "Wood Aged Beer",
                'abv' => 12.0,
                'complexity' => "ADVENTUROUS",
                'section_id' => 1,
            ],
            [
                'id' => 5,
                'brewer' => "The Marsden Brewhouse",
                'name' => "MARSDEN NEOPOLITAN PORTER",
                'description' => "Marsden Neopolitan Porter - Just like the ice cream, Berry - Vanilla - Chocolate! It's a different take on our usual Chocolate Porter with the three distinct ingredients combining to create a triumvirate of flavour! Try it with a piece of Chocolate Mudcake or maybe just a piece of chocolate!",
                'style' => "Stout - Tropical",
                'abv' => 5.5,
                'complexity' => "STEPPING UP",
                'section_id' => 1,
            ],
            [
                'id' => 6,
                'brewer' => "The Mill Brewery",
                'name' => "GO! GO! ICHIGO!",
                'description' => "Umami! Salty! Strawberry! Sour!",
                'style' => "Sour - Gose",
                'abv' => 5.5,
                'complexity' => "STEPPING UP",
                'section_id' => 1,
            ],
            [
                'id' => 7,
                'brewer' => "Hop Nation Brewing Co",
                'name' => "MARKET 2023",
                'description' => "Kaffir lime leaf, mango, coriander, Vietnamese mint and chilli have been integrated into this juicy IPA. A fun and exciting voyage that will take IPA fans through to the flavours of fusion.",
                'style' => "IPA - New England",
                'abv' => 6.0,
                'complexity' => "STEPPING UP",
                'section_id' => 1,
            ],
            [
                'id' => 8,
                'brewer' => "Bad Shepherd Brewing Co",
                'name' => "BARREL AGED RUM DOUBLE CHOC BROWN ALE",
                'description' => "A smooth, toasty and malty brown ale brewed with real hazelnuts, vanilla, cocoa, Jimmy Rum and a splash of Frangelico, this tempting brew was squirreled away by our brewers into Rum barrels. The result is a rich and decadent Double Choc Hazelnut Brown Ale with plenty of character.",
                'style' => "Specialty Beer",
                'abv' => 7.5,
                'complexity' => "ADVENTUROUS",
                'section_id' => 1,
            ],
            [
                'id' => 9,
                'brewer' => "Yenda Brewing Co",
                'name' => "I AM WEISS",
                'description' => "An Australian style wheat beer with the fruitiness of raspberries to pack a zingy punch for this sessional and very quaffable beer.",
                'style' => "Weizen/Weissbier/Hefeweizen",
                'abv' => 6.0,
                'complexity' => "EASY DRINKING",
                'section_id' => 1,
            ],
            [
                'id' => 10,
                'brewer' => "B.O.B",
                'name' => "TIM, TAM & TOM",
                'description' => "Classical British Ale with Tim Tams. Front palate will have loads of biscuitiness, followed by a mid palette showing some hoppy character followed by a sweet lasting finish.",
                'style' => "Brown Ale - UK",
                'abv' => 5.9,
                'complexity' => "EASY DRINKING",
                'section_id' => 1,
            ],
            [
                'id' => 11,
                'brewer' => "The Zythologist",
                'name' => "MOLECULAR BUBBLE TEA IPA",
                'description' => "A decadent Milkshake IPA brewed with purple taro, milk sugar, brown sugar, tapioca, wheat and oats. Complimentary use of floral & fruity hops with a subtle bitter bite reminds you this is still very much a beer, but one that's impostering the Chemistry of a refreshing taro bubble tea.",
                'style' => "IPA - Milkshake",
                'abv' => 6.2,
                'complexity' => "STEPPING UP",
                'section_id' => 1,
            ],
            [
                'id' => 12,
                'brewer' => "Sauce Brewing Co",
                'name' => "LAVENDER CHEESECAKE",
                'description' => "The name says it all! This rich desert sour has delicate lavender aromas with a cheesy (in a good way) twist. Contains lactose.",
                'style' => "Sour - Pastry",
                'abv' => 8.0,
                'complexity' => "ADVENTUROUS",
                'section_id' => 1,
            ],
            [
                'id' => 13,
                'brewer' => "St Andrews Beach Brewery",
                'name' => "SAB LITE",
                'description' => "A crushable American Light Lager brewed with a classic malt profile of pilsner malt, rice and corn.",
                'style' => "Lager - Pale",
                'abv' => 4.5,
                'complexity' => "EASY DRINKING",
                'section_id' => 1,
            ],
            [
                'id' => 14,
                'brewer' => "Local Brewing Co",
                'name' => "DON'T GO BAKING MY HEART (NITRO CINNAMON PASTRY STOUT)",
                'description' => "Crafted with passion and heart using leftover scrolls from a local bakery, the warm and 'dough-lightful' aroma of cinnamon will immediately transport you to a cozy place, inviting you to take a sip of the rich and creamy body. The pronounced sweetness of the pastry perfectly balances with the boldness of the 8% ABV, creating an intense flavour combination.",
                'style' => "Stout - Pastry",
                'abv' => 8.0,
                'complexity' => "ADVENTUROUS",
                'section_id' => 1,
            ],
            [
                'id' => 15,
                'brewer' => "Feral Brewing Co",
                'name' => "CHERRY MAGUIRE",
                'description' => "Sweet cherries create an acidic fruit burst, balancing out the tartness of this sour, with interwoven notes of fluffy pastry and vanilla crisscrossing like a classic cherry pie.",
                'style' => "Sour - Pastry",
                'abv' => 6.5,
                'complexity' => "STEPPING UP",
                'section_id' => 1,
            ],
            [
                'id' => 16,
                'brewer' => "Urban Alley Brewery",
                'name' => "THE TAVERNER ALL BRUT LOW GLUT",
                'description' => "Talus & Citra craft layered waves of tropical fruit melded with spicy Belgian yeast, all tied up in a lean and dry frame with low carbs, low gluten and loads of flavour.",
                'style' => "IPA - White",
                'abv' => 7.0,
                'complexity' => "ADVENTUROUS",
                'section_id' => 1,
            ],
            [
                'id' => 17,
                'brewer' => "Co-Conspirators Brewing",
                'name' => "THE LOVER",
                'description' => "Not only for the sweet tooth inclined drinker, this dessert stout is melding the flavours of caramel, chocolate and soy sauce to create a balanced and complex delight. The Lover will tantalise your tastebuds with the rich flavours of chocolate and caramel and balance that sweetness with the umami and salinity of soy sauce.",
                'style' => "Stout - Pastry",
                'abv' => 8.0,
                'complexity' => "ADVENTUROUS",
                'section_id' => 1,
            ],
            [
                'id' => 18,
                'brewer' => "Escape Brewing",
                'name' => "ESCAPE WITH THE SCHWARTZ",
                'description' => "A clean German style dark lager (Schwarzbier) to delight dark beer lovers and newcomers alike through its smooth malt and dry finish with hints of mint.",
                'style' => "Lager - Dark",
                'abv' => 5.0,
                'complexity' => "EASY DRINKING",
                'section_id' => 1,
            ],
            [
                'id' => 19,
                'brewer' => "Big Shed Brewing Concern",
                'name' => "ONLY FLANS",
                'description' => "Subscribe to our OnlyFlans, a vanilla custard, fruited sour. No monthly fees just explicit deliciousness. Coming in at a suggestive 6.9% with all the classic vanilla custardy goodness, paired with fruits and thick mouthfeel, it puts the phrase 'limited release' into a whole new context….",
                'style' => "Sour - Pastry",
                'abv' => 6.9,
                'complexity' => "STEPPING UP",
                'section_id' => 1,
            ],
            [
                'id' => 20,
                'brewer' => "Seeker Brewing",
                'name' => "UNICORN NEIPA",
                'description' => "For this year's GABS special, all of our mystical energy was channeled into a beer that can only be described as a Unicorn. It boasts a familiar, tropical, juicy flavour and a sprinkle of magic that may have you questioning whether it ever existed at all. The rest of the tasting notes - we leave to you.",
                'style' => "IPA - New England",
                'abv' => 7.2,
                'complexity' => "ADVENTUROUS",
                'section_id' => 1,
            ],
            [
                'id' => 21,
                'brewer' => "Resin Brewing",
                'name' => "CALYPSO",
                'description' => "With pineapple notes up-front, Calypso is the juicy, easy-drinking brew you've been waiting for.",
                'style' => "IPA - Hazy",
                'abv' => 6.0,
                'complexity' => "EASY DRINKING",
                'section_id' => 2,
            ],
            [
                'id' => 22,
                'brewer' => "Catchment Brewing Co",
                'name' => "LONG ISLAND ICED TEA SOUR",
                'description' => "Ahh the Long Island Iced Tea. A cocktail that many know, but don't understand. Big, bold cola flavour, with citrus notes from lemon and orange giving the sour touch. Balanced out with the sweetness of the expected booze sitting at 7.5%. It's special, it's delightful, it's GABS baby!",
                'style' => "Sour - Kettle Sour",
                'abv' => 7.5,
                'complexity' => "ADVENTUROUS",
                'section_id' => 2,
            ],
            [
                'id' => 23,
                'brewer' => "Psycho Suzie's Brewing",
                'name' => "UPPER MANAGEMENT",
                'description' => "Malt biscuity backbone, with a west coast style bitterness and piney-ness. Followed with aromas of stone fruit and resin.",
                'style' => "IPA - Red",
                'abv' => 8.5,
                'complexity' => "ADVENTUROUS",
                'section_id' => 2,
            ],
            [
                'id' => 24,
                'brewer' => "Noodledoof",
                'name' => "DESERT LIME GIMLET IPA",
                'description' => "The flavor is citrus forward with a helping hand from Australian Native Desert Limes that bring a vibrant mandarin flavor. We utilise the heads of our own Koroit Gin, packed full of citrus oils that are a bit too intense for our gin but are a perfect fit for this IPA.",
                'style' => "Specialty Beer",
                'abv' => 6.8,
                'complexity' => "STEPPING UP",
                'section_id' => 2,
            ],
            [
                'id' => 25,
                'brewer' => "Wayward Brewing Co",
                'name' => "VIOLET BEAUREGARDE'S BLUEBERRY MARSHMALLOW LACTOSE SOUR ALE",
                'description' => "Transport yourself to Willy Wonka's factory. Tart, juicy blueberries come together with the subtle sweetness of marshmallow and a smooth, creamy mouthfeel.",
                'style' => "Sour - Pastry",
                'abv' => 4.0,
                'complexity' => "EASY DRINKING",
                'section_id' => 2,
            ],
            [
                'id' => 26,
                'brewer' => "Batch Brewing Co",
                'name' => "AUGUSTUS GLOOP'S CHOC FUDGE PEANUT BRITTLE STOUT",
                'description' => "Roasty notes of chocolate and caramel are met by the nuttiness of peanut brittle and the creamy sweetness of vanilla.",
                'style' => "Stout - Pastry",
                'abv' => 6.0,
                'complexity' => "STEPPING UP",
                'section_id' => 2,
            ],
            [
                'id' => 27,
                'brewer' => "Blackman's Brewery",
                'name' => "RED FROG, RASPBERRY DARK LAGER",
                'description' => "A dark lager made with copious amounts of red frogs and Raspberries. A crisp easy-drinking beer with a fruity Choc berry explosion of red frog delight!",
                'style' => "Lager - Dark",
                'abv' => 5.0,
                'complexity' => "EASY DRINKING",
                'section_id' => 2,
            ],
            [
                'id' => 28,
                'brewer' => "Coldstream Brewery",
                'name' => "CHERRY FRUITED BRAGGOT",
                'description' => "A blend of a heavily cherry-fruited Saison and a Braggot brewed with local honey. Luscious and sweet with a dry finish, aromatic cherry and honey flavours, and an unmistakable Saison spice.",
                'style' => "Braggot",
                'abv' => 6.5,
                'complexity' => "",
                'section_id' => 2,
            ],
            [
                'id' => 29,
                'brewer' => "Good Land Brewing Co",
                'name' => "BANANARAMA PINA COLADA",
                'description' => "Banana Pina Colada is our super smoothie base with Banana, Marshmallow, Coconut & Pineapple. Contains Lactose.",
                'style' => "Sour - Fruit",
                'abv' => 5.8,
                'complexity' => "EASY DRINKING",
                'section_id' => 2,
            ],
            [
                'id' => 30,
                'brewer' => "Precinct Brewing",
                'name' => "THROWING HAZE",
                'description' => "This stack of hop character is built upon a solid malt base containing multiple types of malted and rolled oats, with a dash of high-quality Yuzu juice. The acidity cuts through on the back end of the palate, snapping in its unique flavor and keeping the mouth wanting more!",
                'style' => "IPA - Hazy",
                'abv' => 6.8,
                'complexity' => "STEPPING UP",
                'section_id' => 2,
            ],
            [
                'id' => 31,
                'brewer' => "King River Brewing",
                'name' => "STICKE COFFEE KOLSCH",
                'description' => "Cold brewed coffee on a double strength \"Sticke\" Kolsch. Deep golden, bready malt base with 100 litres of coffee from our local Coffee roaster. This won't just wake you up in the morning, it'll make sure you feel great about the day too. At least for the first part of the day",
                'style' => "Kölsch",
                'abv' => 7.0,
                'complexity' => "ADVENTUROUS",
                'section_id' => 2,
            ],
            [
                'id' => 32,
                'brewer' => "Black Hops Brewery",
                'name' => "SQUISHEE",
                'description' => "High sweetness and thick mouthfeel with a large fruit addition of Strawberry and Lime as the beer will be offered as a slushee at our stall as well as on tap.",
                'style' => "Sour - Kettle Sour",
                'abv' => 6.5,
                'complexity' => "STEPPING UP",
                'section_id' => 2,
            ],
            [
                'id' => 33,
                'brewer' => "Deeds Brewing",
                'name' => "PEANUT BUTTER BROWNIE IMPERIAL STOUT",
                'description' => "A delicious and indulgent treat that combines rich chocolate, creamy peanut butter, and roasty stout flavors. The taste is smooth, rich and chocolatey, with a creamy peanut butter flavor that complements the fudgy, brownie-like sweetness, and the mouthfeel is full and velvety.",
                'style' => "Stout - Imperial",
                'abv' => 10.0,
                'complexity' => "ADVENTUROUS",
                'section_id' => 2,
            ],
            [
                'id' => 34,
                'brewer' => "Blackflag Brewing",
                'name' => "BARELY LEGAL",
                'description' => "Its big, bold and barely legal. Nice rounded Quad IPA packing a punch. It's bitter, boozy and something to tell your friends about.",
                'style' => "IPA - Imperial",
                'abv' => 18.1,
                'complexity' => "ADVENTUROUS",
                'section_id' => 2,
            ],
            [
                'id' => 35,
                'brewer' => "Five' 3\" Brewing",
                'name' => "MUNICH DUNKEL",
                'description' => "Subtle sweet notes of toffee with light floral and herbal aroma with some spice added in.",
                'style' => "Munich Dunkel",
                'abv' => 5.0,
                'complexity' => "EASY DRINKING",
                'section_id' => 2,
            ],
            [
                'id' => 36,
                'brewer' => "Bonehead Brewing",
                'name' => "THROAT POUR",
                'description' => "When you need something to remind you why you first fell in love with craft beer. Throat Pour is a Classic German Pilsner, featuring Tettnanger and Perle hops, making it a refreshing crispy-boi with a subtle spice and pine finish and gentle floral aroma.",
                'style' => "Lager - Classic German Pilsner",
                'abv' => 5.1,
                'complexity' => "EASY DRINKING",
                'section_id' => 2,
            ],
            [
                'id' => 37,
                'brewer' => "Revel Brewing Co.",
                'name' => "BLACK FORREST CAKE SOUR",
                'description' => "Luscious & divine, who can resist a slice of Black Forrest Cake? Dark Chocolate, Coffee, and Black Cherry with a creamy smooth body topped off by a bitey acidity to finish.",
                'style' => "Sour - Pastry",
                'abv' => 6.0,
                'complexity' => "STEPPING UP",
                'section_id' => 2,
            ],
            [
                'id' => 38,
                'brewer' => "Pixel Brewing",
                'name' => "PEAK HYPE",
                'description' => "Featuring Nectaron, the latest and greatest hop released by NZ Hops teamed up with one of our other local favourites in Vic Secret for a tropical fruit punch to the face. A clean and light malt base showcasing the hops.",
                'style' => "IPA - American",
                'abv' => 6.5,
                'complexity' => "STEPPING UP",
                'section_id' => 2,
            ],
            [
                'id' => 39,
                'brewer' => "Bright Brewery",
                'name' => "DRINKIN' DONUTS IMPERIAL JAM DONUT GOLDEN ALE",
                'description' => "Is there anything more iconic than the Hot Jam Donut? Sugar, spice, and all things nice - not to mention oozing with sweet raspberry jam. Bright Brewery's Drinkin' Donuts Imperial Jam Donut Golden Ale will transport you directly to beer drinkin' heaven!",
                'style' => "Experimental Beer",
                'abv' => 8.0,
                'complexity' => "ADVENTUROUS",
                'section_id' => 2,
            ],
            [
                'id' => 40,
                'brewer' => "Wolf of the Willows",
                'name' => "THE SNOWBALL EFFECT",
                'description' => "Imperial Stout aged in whisky barrels for 9 months, finished on cocoa nibs, vanilla and coconut. Contains lactose.",
                'style' => "Stout - Pastry",
                'abv' => 10.5,
                'complexity' => "ADVENTUROUS",
                'section_id' => 2,
            ],
            [
                'id' => 41,
                'brewer' => "Braeside Brewing Co",
                'name' => "RYE RYE RYE DELIAH",
                'description' => "Rye not give it a go, a bright red ipa packed with rye malt, chuck in Darjeeling tea leaf and you find yourself in a cross continent heaven. Crazy aromatic with a spicy toffee malt build.",
                'style' => "IPA - Red",
                'abv' => 6.5,
                'complexity' => "STEPPING UP",
                'section_id' => 3,
            ],
            ['id' => 42,    'brewer' => "Badlands Brewery",    'name' => "GRANDMERE'S CRUMBLE\" RHUBARB & CUSTARD (APPLE) SAISON",    'description' => "Tassie Rhubarb, QLD Custard Apples & a French farmhouse beer style. Piquant, smooth and gentle. Comfort Food in a glass",    'style' => "Saison/Farmhouse Ale",    'abv' => 6.0,    'complexity' => "STEPPING UP",    'section_id' => 3,],
            ['id' => 43,    'brewer' => "Moffat Beach Brewing Co",    'name' => "CAN'T BEET A ROOT",    'description' => "Beetroot. Whether it\'s leaking the red stuff all over your burger with the lot, or \'garnishing\' your Mum\'s iceberg lettuce \'salad\', is there any veg more quintessentially Australian? Well, we\'ve taken it one step further, and whacked it in a beer. That\'s right. Beetroot. In. Your. Beer. Can\'t beet it.",    'style' => "Lager - Classic Pilsner",    'abv' => 4.8,    'complexity' => "STEPPING UP",    'section_id' => 3,],
            ['id' => 44,    'brewer' => "Shifty Lizard Brewing Co.",    'name' => "COTTON CANDY SOUR",    'description' => "Like flying swiftly over the rainbow, this kettle sour is as much sweet as it is sour and tart. A balance that will take you back to the side show alley while still puckering lips and clicking your tongue on the roof of your mouth!",    'style' => "Sour - Kettle Sour",    'abv' => 4.8,    'complexity' => "EASY DRINKING",    'section_id' => 3,],
            ['id' => 45,    'brewer' => "Craft and Co.",    'name' => "THE CRAFT AND CO. WIPA",    'description' => "A wheat-based IPA brewed exclusively with Australian ingredients. Bursting with bright citrus, stone fruit, and tropical flavors. Fermented with a clean ale to allow big hop flavor to be showcased, with a smooth, creamy, refreshing, wheat back bone.",    'style' => "IPA - Imperial",    'abv' => 6.5,    'complexity' => "STEPPING UP",    'section_id' => 3,],
            [
                'id' => 46,
                'brewer' => "Tallboy and Moose",
                'name' => "WAGGLE BUZZ",
                'description' => "Ah, the braggot! A perfect blend of mead and beer, a liquid love story in your glass. Honey undertones mingle with caramel and biscuit flavours care of Cara Amber and Munich malts. Get your waggle on!",
                'style' => "Braggot",
                'abv' => 6.6,
                'complexity' => "STEPPING UP",
                'section_id' => 3,
            ],
            [
                'id' => 47,
                'brewer' => "Reckless Brewing Co",
                'name' => "BOGAN FUEL",
                'description' => "Rev your engines for a lip-smacking supercharged sip of sheer westie goodness with Bogan Fuel, especially for GABs. Take your classic rum and cola and redline the flavour with a sour twist, and there you have it – all the power and grunt of a V8 in a can, with a punch like a polar bear and a winning finish like Craig Lowndes at his cracking best.",
                'style' => "Specialty Beer",
                'abv' => 6.9,
                'complexity' => "STEPPING UP",
                'section_id' => 3,
            ],
            [
                'id' => 48,
                'brewer' => "Modus Brewing",
                'name' => "CHROME FURY",
                'description' => "A mango dessert in liquid form. Delicious fruity flavours with a hit of vanilla, delivering the ultimate blend of sweet with a slap of sour at the end.",
                'style' => "Sour - Pastry",
                'abv' => 6.0,
                'complexity' => "STEPPING UP",
                'section_id' => 3,
            ],
            [
                'id' => 49,
                'brewer' => "Aether Brewing",
                'name' => "BISCOFF ICE CREAM PORTER",
                'description' => "A delicious, smooth, rich and decadent porter base that is dripping with biscoff and vanilla! Aromas of the namesake biscuit along with subtle roasted malts combine to offer a mildly sweet treat that will leave you drooling for more!",
                'style' => "Experimental Beer",
                'abv' => 8.0,
                'complexity' => "ADVENTUROUS",
                'section_id' => 3,
            ],

            [
                'id' => 50,
                'brewer' => "Eumundi Brewery",
                'name' => "GINGER NUT SPARKLING IPA",
                'description' => "We hail form the best ginger growing region in the country, and we love our beer and biscuits. This is our Brut IPA with classic overtones of ginger, cinnamon, and brown sugar all in one glass.",
                'style' => "IPA - Brut",
                'abv' => 6.0,
                'complexity' => "STEPPING UP",
                'section_id' => 3,
            ],
            [
                'id' => 51,
                'brewer' => "Stoic Brewing",
                'name' => "IMPERIAL LEMON MERINGUE TART SOUR",
                'description' => "We\'ve used a new novel yeast foraged locally by Mogwai Yeast Labs that ferments and sours as well! It gives zesty citrus character that we\'ve bumped up to 11 with real lemon puree. We\'ve used Biscuit malt from Voyager Craft Malt to give that tart crust flavour along with oats, vanilla and lactose to produce a full on flavour bomb that\'s silky, smooth, tart and rounded. An ode to all our favourite grandmas classic dessert.",
                'style' => "Sour - Pastry",
                'abv' => 8.3,
                'complexity' => "ADVENTUROUS",
                'section_id' => 3,
            ],
            [
                'id' => 52,
                'brewer' => "Mismatch Brewing Co",
                'name' => "HOP QUAD BUNS",
                'description' => "If a Belgian baker started brewing and only made beers that tasted like they came from a bakery, you would have Hop Quad Buns. Everybody\'s Easter favourite, Hot Cross Buns combined with a big Belgian Quad. Expect dark fruit and sweetness, with the spice of a Hot Cross Bun.",
                'style' => "Belgian Quad",
                'abv' => 10.5,
                'complexity' => "STEPPING UP",
                'section_id' => 3,
            ],
            [
                'id' => 53,
                'brewer' => "Merino Brewery",
                'name' => "MULBERRY BUSH IMPERIAL IPA",
                'description' => "Fruited beer that\'s not sour! A bucket load of Mulberries and then some more added to this beer giving a good balance of sweet and tart flavours with a hint of woody cedar to bridge the piney bitterness an of an American classic. This imperial edition certainly slaps the right notes, in all areas.",
                'style' => "IPA - Black",
                'abv' => 7.5,
                'complexity' => "STEPPING UP",
                'section_id' => 3,
            ],
            [
                'id' => 54,
                'brewer' => "Working Title Brew Co",
                'name' => "TAKE 5 - CHOC CARAMEL PEANUT BUTTER CUP DOUBLE MILK STOUT",
                'description' => "Everyone needs a break. Hell, you know you\'ve earned it. So take five and lose yourself in a big, chewy choc caramel peanut butter cup beersplosion that\'s guaranteed to make you regret not taking the whole day off. First up, decadent caramel and rich peanut butter whack you right in the schnozarooni. Layers of chocolate and caramel malt complexity blend intricately with the peanuts and a decadent, muscovado body. A saline body lifts the overall flavours for one hell of a savoury peanut butter cup experience that will leave you gagging for more.",
                'style' => "Stout - Pastry",
                'abv' => 8.0,
                'complexity' => "ADVENTUROUS",
                'section_id' => 3,
            ],
            [
                'id' => 55,
                'brewer' => "Capital Brewing Co",
                'name' => "SALVAGED SOUR - APPLE & RHUBARB CRUMBLE PASTRY IMPERIAL SOUR",
                'description' => "Brewed using ingredients that would\'ve been thrown out. \'Ugly\' apples and rhubarb were sourced from a local farmer and given a second life. This sweet biscuity base beer is loaded with a heap of specialty malts to give you a brown sugar and honey crumble flavour and is the perfect balance of sweet & sour. *Contains lactose.",
                'style' => "Sour - Pastry",
                'abv' => 10.0,
                'complexity' => "ADVENTUROUS",
                'section_id' => 3,
            ],
            [
                'id' => 56,
                'brewer' => "Common Ground Brewing",
                'name' => "BLOODY MISTIC",
                'description' => "Our Blood Orange and Sage Wheat pours a golden straw colour with plenty of haze topped with a fluffy white head of foam. The aroma is juicy and somewhat spicy, earthy, floral character with an undercurrent of wheat. On the palate, look for a nice breadiness at the centre of this beer with a big juicy and herbal hit from the blood orange and sage followed with some mild bitterness.",
                'style' => "American Wheat",
                'abv' => 6.0,
                'complexity' => "STEPPING UP",
                'section_id' => 3,
            ],
            [
                'id' => 57,
                'brewer' => "Slipstream Brewing Co",
                'name' => "MAPLE BACON PANCAKE STOUT",
                'description' => "Picture a tall stack of fluffy pancakes, topped with maple bacon and vanilla ice cream, and an extra drizzle of maple syrup for good health. Now picture it in stout form - what a delicious start to the day! This decadent milk stout features a fluffy mouthfeel, and is stacked with flavours of sweet maple, vanilla, smoky bacon, toast and roast.",
                'style' => "Stout - Sweet Stout",
                'abv' => 7.0,
                'complexity' => "STEPPING UP",
                'section_id' => 3,
            ],
            [
                'id' => 62,
                'brewer' => "Valley Hops Brewing",
                'name' => "THE NUGGET",
                'description' => "100% fermented with wild yeast, this Aussie IPA is surprisingly clean while boasting ripe pineapple, peach and citrus with just the right amount of funk.",
                'style' => "Wild Australian IPA",
                'abv' => 6.5,
                'complexity' => "STEPPING UP",
                'section_id' => 4,
            ],
            [
                'id' => 63,
                'brewer' => "Stomping Ground Brewing Co",
                'name' => "BUCK YEAH",
                'description' => "In true Capricorn style, Buck Yeah Eisbock set its sights on being the G.O.A.T. The strongest, most ambitious beer in Stomping Ground\'s zodiac beer line up. Stored below freezing temp, this beast of a brew hoofed it to a huge 13% ABV. With caramel, dark fruit and molasses notes, it\'s an overachiever that\'s sure to float your goat.",
                'style' => "Eisbock",
                'abv' => 13.0,
                'complexity' => "ADVENTUROUS",
                'section_id' => 4,
            ],
            [
                'id' => 64,
                'brewer' => "Burleigh Brewing",
                'name' => "BURLEIGH BLACK GIRAFFE DOUBLE SHOT.",
                'description' => "Brewed in collaboration with a local coffee roaster; imperial black coffee lager.",
                'style' => "Lager - Imperial Pils/Lager",
                'abv' => 8.0,
                'complexity' => "ADVENTUROUS",
                'section_id' => 4,
            ],
            [
                'id' => 65,
                'brewer' => "Your Mates Brewing Co",
                'name' => "IMPERIAL WHITE CHOC & MACADAMIA STOUT",
                'description' => "We\'ve taken a big abv stout, pulled out the darkness and infused it with the richest of white chocolate sauce and macadamia to create a fancy AF desert beer. Isn\'t a stout supposed to be dark you say? We have used all pale malts with cocoa nibs & coffee beans to inject all the roastiness of a stout but the colour of a milky bar!",
                'style' => "Stout - Imperial",
                'abv' => 9.0,
                'complexity' => "ADVENTUROUS",
                'section_id' => 4,
            ],
            [
                'id' => 66,
                'brewer' => "Willie The Boatman",
                'name' => "WEEKEND AT WILLIES",
                'description' => "It\'s a beach holiday, Weekend at Willies!! We have put together a fresh and tropical kettle sour, utilising every tropical fruit we could get our hands on. Dry hopped with Sabro and added toasted coconut and vanilla, it will whisk you away to a beach from long ago, drinking cocktails on the sand while watching the waves roll in. Come join us for a Weekend at Willies !!",
                'style' => "Sour - Kettle Sour",
                'abv' => 6.5,
                'complexity' => "STEPPING UP",
                'section_id' => 4,
            ],
            [
                'id' => 67,
                'brewer' => "Shark Island Brewing Co",
                'name' => "LIFE CAN BE SWEET & SOUR",
                'description' => "The Grumpy Brewer was celebrating his Wedding Anniversary and ordering takeaway when he spilt some champagne on his laptop that froze the screen on Sweet & Sour Pork... which inspired him to create a zesty Saison infused with Cinnamon and Pineapple. Expect a crisp, refreshing sweet and spicy drop.",
                'style' => "Specialty Beer",
                'abv' => 6.9,
                'complexity' => "STEPPING UP",
                'section_id' => 4,
            ],
            [
                'id' => 68,
                'brewer' => "Heroes and Villains",
                'name' => "FISTS OF FIORI",
                'description' => "Looks like an IIPA, the underlying beer and profile is IIIPA. The flavour is a big AF coffee espresso. The coffee beans are roasted only for this brew. The coffee roasters would describe the bean flavours as \"purple\". This will blow your mind!",
                'style' => "Sour - Pastry",
                'abv' => 6.0,
                'complexity' => "STEPPING UP",
                'section_id' => 4,
            ],
            [
                'id' => 69,
                'brewer' => "Jetty Road Brewery",
                'name' => "BARREL-AGED RASPBERRY IMPERIAL STOUT",
                'description' => "Boasts a strong aroma of dark roasted malts along with rich decadent layers of chocolate, coffee and a raspberry punch to finish. Just like a Black Forrest cake your nan made for afternoon tea.",
                'style' => "Stout - Imperial",
                'abv' => 10.0,
                'complexity' => "ADVENTUROUS",
                'section_id' => 4,
            ],
            [
                'id' => 70,
                'brewer' => "Dainton Beer",
                'name' => "CHOC BERRY BOMB",
                'description' => "Get ready to experience a Berliner Weisse like never before! A sour beer bursting with the sweet and tangy flavors of dark berries, complemented perfectly with hints of decadent chocolate. Served on nitro, it\'s the ultimate refreshing sipper with a luxuriously creamy texture.",
                'style' => "Sour - Berliner Weisse",
                'abv' => 7.0,
                'complexity' => "STEPPING UP",
                'section_id' => 4,
            ],
            [
                'id' => 71,
                'brewer' => "Warrandyte Brewing Co",
                'name' => "DAYUMMM",
                'description' => "Brewed as a traditional Schwarzbier, this easy drinking, crisp dark Lager has hints of chocolate and coffee on the nose and on the taste buds. Tipping our hat at tradition, whilst putting our own unique spin on a great winter beer.",
                'style' => "Schwarzbier",
                'abv' => 5.5,
                'complexity' => "EASY DRINKING",
                'section_id' => 4,
            ],
            [
                'id' => 72,
                'brewer' => "Frenchies Brewery",
                'name' => "TROPO-THIOL",
                'description' => "The Tropo-Thiol will be the latest in our IPA collab series with Freestyle Hops and Hopsters. It\'s a super juicy Double IPA that will showcase the brand new TropicAle yeast from White Labs, plus feature thiol precursor packed Freestyle Hops from New Zealand\'s Nelson Valley, and it\'ll be topped with their innovative SubZero Hop Kief oils.",
                'style' => "Imperial IPA",
                'abv' => 8.0,
                'complexity' => "STEPPING UP",
                'section_id' => 4,
            ],
            [
                'id' => 73,
                'brewer' => "Sydney Brewery",
                'name' => "G AND T GOSE",
                'description' => "Easy drinking Gose style with juniper berry and cucumber notes. This is a refreshing twist on the Hendricks and cucumber G and T.",
                'style' => "Sour - Goser",
                'abv' => 5.0,
                'complexity' => "EASY DRINKING",
                'section_id' => 4,
            ],
            [
                'id' => 74,
                'brewer' => "Mountain Culture Beer Co",
                'name' => "BALLOON ANIMALS",
                'description' => "This juicy treat has been loaded up with Madagascan vanilla beans and heavy additions of Peacherine from Freestyle Hops over in New Zealand which are known for its intense peach flavours. The addition of creamy lactose sugars gives this beer a silky smooth body and complements the sweetness of the vanilla almost like a peaches and cream dessert.",
                'style' => "IPA - Milkshake",
                'abv' => 7.5,
                'complexity' => "STEPPING UP",
                'section_id' => 4,
            ],
            [
                'id' => 75,
                'brewer' => "Mountain Goat",
                'name' => "GARTH'S FAVE PUNCH BOWL",
                'description' => "Tiki-style rum barrel sour cocktail. Tropical fruit sour ale blended with pineapple juice and fermented in rum barrels with two strains of yeast.",
                'style' => "Specialty Beer",
                'abv' => 6.5,
                'complexity' => "STEPPING UP",
                'section_id' => 4,
            ],
            [
                'id' => 76,
                'brewer' => "Westside Ale Works",
                'name' => "MIND-BOTTLING, ISN'T IT?",
                'description' => "Be prepared to have your mind bottled! We have brewed our largest Imperial Stout to date! Rich dark roasted malts giving chocolate and espresso vibes. Balanced with hops and the addition of bourbon and rum oak staves. Did you just say, \'mind-bottling?'",
                'style' => "Stout - Imperial",
                'abv' => 18.0,
                'complexity' => "ADVENTUROUS",
                'section_id' => 4,
            ],
            [
                'id' => 77,
                'brewer' => "ATOMIC",
                'name' => "VOVO WHIP",
                'description' => "Modelled off the treasured biscuit favourite served by Nans around Australia, this Raspberry Coconut Sour tastes exactly as it sounds. Tart, refreshing and delightfully nostalgic.",
                'style' => "Sour - Kettle Sour",
                'abv' => 4.5,
                'complexity' => "EASY DRINKING",
                'section_id' => 4,
            ],
            [
                'id' => 78,
                'brewer' => "Katoomba Brewing Co.",
                'name' => "MOUNTAIN SUNSET",
                'description' => "We\'ve been rotating our way through some of the newer hop varieties of late and one that really blew our socks off as soon as we opened the bag was Nectaron. NZ\'s flagship hop bursts with tropical pineapple, passionfruit, peach & grapefruit. Add that to one of our other favourite hops Vic Secret which features stupid amounts of tropical pineapple and a hint of pine and you can\'t really go wrong.",
                'style' => "IPA - Red",
                'abv' => 6.5,
                'complexity' => "STEPPING UP",
                'section_id' => 4,
            ],
            ['id' => 79,    'brewer' => "Soapbox Beer",    'name' => "MANGO STORMY",    'description' => "You\'d be surprised if it didn\'t taste like mango beer but do you know what else is hidden in this dark malty lager? The thunderstorms of the sub tropics have inspired a gingered malt forward mango storm. Come find out what else is lurking in the dark.",    'style' => "Lager - Dark",    'abv' => 5.2,    'complexity' => "STEPPING UP",    'section_id' => 4,],
            ['id' => 81,    'brewer' => "Quakers Hat Brewing",    'name' => "BRUT IPA",    'description' => "A bone dry finish and big fruity hop flavour, coupled with high carbonation make this big boozy IPA super refreshing!",    'style' => "IPA - Brut",    'abv' => 6.3,    'complexity' => "STEPPING UP",    'section_id' => 5,],
            ['id' => 82,    'brewer' => "Brewmanity Beer Co",    'name' => "SMOKEY BACON BALLS",    'description' => "Your old school favourite snack, but it\'s better as a beer! As a certain Cheetah may or may not have said \"Dangerously smokey\"",    'style' => "Rauchbier",    'abv' => 7.0,    'complexity' => "ADVENTUROUS",    'section_id' => 5,],
            ['id' => 83,    'brewer' => "Beerfarm",    'name' => "ALMIGHTY ASAM",    'description' => "We thought the curious Asam Boi salted plum would make the perfect weird and wonderful addition to a gose for their intense saltiness, dried plum character and vibrant colour. A German classic with an Asian twist, expect tartness as bright as it\'s colour, and an almighty ABV to match.",    'style' => "Sour - Gose",    'abv' => 7.8,    'complexity' => "ADVENTUROUS",    'section_id' => 5,],
            [
                'id' => 84,
                'brewer' => "Currumbin Valley Brewing",
                'name' => "CHEERY RIPE PORTER",
                'description' => "A velvety, smooth chocolate brown porter with cherries, cacao & toasted coconut. Inspired by the popular Cherry Ripe chocolate bar!",
                'style' => "Brown Porter",
                'abv' => 4.8,
                'complexity' => "STEPPING UP",
                'section_id' => 5,
            ],
            [
                'id' => 85,
                'brewer' => "Woolshed Brewery",
                'name' => "WOOLSHED BREWERY AND VILI\'S FAMILY BAKERY MEAT PINT",
                'description' => "Partnering with South Australian pie icons Vili\'s, we present a spicy dark beer brewed with the secret flavour mix used in Vili\'s legendary meat pies to create.. Meat Pint.",
                'style' => "Specialty Beer",
                'abv' => 7.2,
                'complexity' => "ADVENTUROUS",
                'section_id' => 5,
            ],
            [
                'id' => 86,
                'brewer' => "TWØBAYS Brewing Co",
                'name' => "PUMPKIN OF LIBERTY IPA",
                'description' => "Brewed with smashed pumpkin and yellow corn malt, then balanced with a late addition of piney and citrusy American hops, we\'ve created a Westcoast IPA with a Southern states twist and without the gluten so everyone can enjoy. Freedom never tasted so good!",
                'style' => "IPA - American",
                'abv' => 7.0,
                'complexity' => "STEPPING UP",
                'section_id' => 5,
            ],
            [
                'id' => 87,
                'brewer' => "Wandana Brewing Co.",
                'name' => "AZTEC (PALE CHOCOLATE LAGER)",
                'description' => "A smooth, easy-drinking pale chocolate lager with a hint of sweetness from the chocolate malt. This beer is perfect for those who want to try something a little different without straying too far from the traditional lager style.",
                'style' => "Lager - Pale",
                'abv' => 4.4,
                'complexity' => "EASY DRINKING",
                'section_id' => 5,
            ],
            ['id' => 88,    'brewer' => "Frexi Brewing",    'name' => "PIZZA BEER",    'description' => "Pizza :D - Tomato, oregano, basil, salt",    'style' => "Sour - Gose",    'abv' => 4.2,    'complexity' => "ADVENTUROUS",    'section_id' => 5,],
            ['id' => 89,    'brewer' => "Snowys Brewery",    'name' => "SNOWY\'S KÖLSCH",    'description' => "A mild aroma with fruity notes and a hint of Pineapple and passionfruit.",    'style' => "Kölsch",    'abv' => 4.9,    'complexity' => "EASY DRINKING",    'section_id' => 5,],
            ['id' => 90,    'brewer' => "Jervis Bay Brewing Co",    'name' => "HYPSTER LATTE STOUT",    'description' => "Rich and full bodied with a smooth coffee finish, brewed with a special blend of coffee beans roasted in-house at a celebrated local coffee roaster. This is our take on a Café Latte Shakerato, with an Irish twist!",    'style' => "Sour - Berliner Weisse",    'abv' => 7.0,    'complexity' => "STEPPING UP",    'section_id' => 5,],
            ['id' => 91,    'brewer' => "Blasta Brewing Co",    'name' => "FRUITS ON FIRE - SPICY SOUR",    'description' => "Inspired by a holiday by the sea. Sunshine, salt air, and a tequila cocktail in your hand but with a spi-sea twist! Strawberry, Pineapple & Lime play host to Jalapeños to add some warmth to this sour.",    'style' => "Strawberry, Pineapple, Lime, and Jalapeno sour",    'abv' => 5.0,    'complexity' => "EASY DRINKING",    'section_id' => 5,],
            ['id' => 92,    'brewer' => "Hawkes Brewing Co",    'name' => "HAWKE\'S BOB HULK DOUBLE HAZY IPA",    'description' => "This sustainability-inspired, dangerously-delicious double hazy IPA is smashed with malted oats, grown by 2022 Landcarer of the Year, Bruce Maynard. It\'s a creamy, hazy, golden flavour storm, unleashing creamy coconut and tropical pineapple and mango, before a shower of citrus fruits and low bitterness lands across the palate. Smash responsibly.",    'style' => "IPA - New England",    'abv' => 8.5,    'complexity' => "ADVENTUROUS",    'section_id' => 5,],
            ['id' => 93,    'brewer' => "Lost Palms Brewing Co",    'name' => "FEEDBACK",    'description' => "Marshmallow, heavy dosing of blackcurrant, blackberry and vanilla. Big & Bold Pastry Sour. Contains lactose",    'style' => "Sour - Pastry",    'abv' => 14.0,    'complexity' => "ADVENTUROUS",    'section_id' => 5,],
            ['id' => 94,    'brewer' => "Malt Shovel Brewers",    'name' => "MSB CHOCOLATE BUBBLE IMPERIAL STOUT",    'description' => "A throwback to a party favourite – chocolate, breakfast cereal that goes pop and coconut all contained in a stout that\'s so big it\'s imperial",    'style' => "Stout - Pastry",    'abv' => 7.1,    'complexity' => "ADVENTUROUS",    'section_id' => 5,],
            ['id' => 95,    'brewer' => "Freshwater Brewing Co",    'name' => "BARREL AGED CERVEZA",    'description' => "Our classic Wedge Cerveza ABV has been beefed up and spent time resting on Mezcal oak which increases the corn and lime flavors whilst also adding an unique minerality, smokey and peppery note that only this mysterious elixir can provide.",    'style' => "Lager - Pale",    'abv' => 6.0,    'complexity' => "STEPPING UP",    'section_id' => 5,],
            ['id' => 96,    'brewer' => "10 Toes Brewing",    'name' => "LIVING THE CREAM",    'description' => "Big Pastry vibes featuring oat malt for body, vanilla bean bringing the dessert, apricot puree for that sweet fruity hit and Sabro for the coconut aromas",    'style' => "IPA - Pastry",    'abv' => 5.8,    'complexity' => "EASY DRINKING",    'section_id' => 5,],
            [
                'id' => 97,
                'brewer' => "Newstead Brewing Co",
                'name' => "FULLY JACKED",
                'description' => "Up at Sparrows fart to sail the seven banks of the Brisbane river, our fleet was plundered by Drunken Pirates. Devastated, we are left to rebuild with the shackles they left behind. A barrel of local rum, in-house caramelised raisins, rich dark molasses and some lactose for those long voyages. It\'s a Yo ho ho and a Bottle of Rum… and Raisin Pud Pastry Stout. Loaded with rum and raisin goodness, balanced with a rich and complex malt profile, decadent molasses, a pleasing bitterness and the sweetness of a pastry stout. It\'s a sipper, one to enjoy while watching the sun set, or rise.",
                'style' => "Rum Porter",
                'abv' => 9.9,
                'complexity' => "ADVENTUROUS",
                'section_id' => 5,
            ],
            [
                'id' => 98,
                'brewer' => "Boatrocker Brewers & Distillers",
                'name' => "GULLS JUST WANNA HAVE FUN (FISH & CHIP GOSE)",
                'description' => "A refreshing and nostalgic seaside sour that will make you want to Flake from work and go straight to your happy Plaice. Briny salinity and umami from the sea harvest ingredients - sea urchin, shellfish shells, sea parsley & samphire - create an unexpectedly moreish drop when combined with fresh lemon peel and the bright and zesty flavours of a traditional gose. The addition of mashed potatoes into the mash (and the opportunity for wordplay here is not lost on us) rounds out this experimental brew with a satisfying familiarity that will have you asking \'where should we go next for ice cream?",
                'style' => "Sour - Gose",
                'abv' => 5.0,
                'complexity' => "EASY DRINKING",
                'section_id' => 5,
            ],
            [
                'id' => 99,
                'brewer' => "Little Creatures",
                'name' => "STOUTINI 2.0",
                'description' => "The GABS exclusive Stoutini is back with a twist! A nitro stout using cold-brewed Mexican coffee. Nitrogen infused for a frothy finish, this smooth, caffeinated wonder is Little Creatures take on the classic espresso martini cocktail.",
                'style' => "Stout - Imperial Nitro Coffee",
                'abv' => 7.8,
                'complexity' => "STEPPING UP",
                'section_id' => 5,
            ],
            [
                'id' => 100,
                'brewer' => "Bentspoke Brewery",
                'name' => "KEEPING IT SIMPLE",
                'description' => "Take the road less travelled. Keeping it Simple is Just Another IPA.",
                'style' => "JAIPA (Just another IPA)",
                'abv' => 6.8,
                'complexity' => "STEPPING UP",
                'section_id' => 5,
            ],
            [
                'id' => 101,
                'brewer' => "Aunty Jacks",
                'name' => "AWW DUCK YEAH!",
                'description' => "Inspired by something truly timeless - the A.W.W. Duck Cake - this Collab beer between Aunty Jacks of Ballarat and Noodledoof of Koroit is a sweet white stout brewed to showcase the hallmarks of the childhood cult classic. Brewed using a variety of specialty malts and rolled oats, sweetened with lactose, then spiced with Vanilla, Cacao, Green Coffee beans and some all-important popcorn, liquorice and crinkle cut chips (the beak!)",
                'style' => "Stout - Sweet Stout",
                'abv' => 5.2,
                'complexity' => "STEPPING UP",
                'section_id' => 6,
            ],
            [
                'id' => 102,
                'brewer' => "Garage Project",
                'name' => "THE WAY OF TEA",
                'description' => "Smooth East Coast style IPA infused with Green Matcha, blending juicy citrus hops with a sweet umami twist of tea.",
                'style' => "IPA - Hazy",
                'abv' => 7.0,
                'complexity' => "ADVENTUROUS",
                'section_id' => 6,
            ],
            [
                'id' => 103,
                'brewer' => "Sierra Nevada",
                'name' => "NO PLACE LIKE AUS",
                'description' => "Australian hops headline this West Coast-style IPA, with Galaxy and Vic Secret teaming up for a Down Under medley of citrus, berries and sweet fruit, all rooted in a clean bitterness from trusty Magnum",
                'style' => "IPA - Hoppy",
                'abv' => 6.5,
                'complexity' => "STEPPING UP",
                'section_id' => 6,
            ],
            [
                'id' => 104,
                'brewer' => "Cloudwater Brew Co.",
                'name' => "PROPER GABS",
                'description' => "The latest in our Proper DIPA series, celebrating a legendary Manchester yeast that has spanned thousands of generations. With the original recipes developed by our pals at JW Lees in 2017, we are continuing their memory through a beer that is modern, bold and supremely hoppy. This time we use bold new Strata hops, bringing a punchy floral and fruity aroma, apricot and melon flavours and full bodied sweetness balanced by a resinous finish.",
                'style' => "IPA - New England (Double)",
                'abv' => 8.0,
                'complexity' => "ADVENTUROUS",
                'section_id' => 6,
            ],
            [
                'id' => 105,
                'brewer' => "Hudson Brewing",
                'name' => "HAIL MARY, HAIR OF THE DOG",
                'description' => "The day after a big night out can be pretty daunting... Jump back in with this refreshing pick-me-up!\"Hail Mary, Hair of the Dog\" - A Tomato Farmhouse style kick starter, a touch of tobassco and a pinch of salt. Welcome back to reality...",
                'style' => "Saison/Farmhouse Ale",
                'abv' => 5.0,
                'complexity' => "ADVENTUROUS",
                'section_id' => 6,
            ],
            [
                'id' => 106,
                'brewer' => "Impi Brewers",
                'name' => "FIERY AZZURRO PILS",
                'description' => "A spicy twist on a classic Italian Pilsner, with a subtle heat from habanero chilli that complements the crisp and refreshing taste. Perfect for a summer day or pairing with spicy foods.",
                'style' => "Specialty Beer",
                'abv' => 6.5,
                'complexity' => "STEPPING UP",
                'section_id' => 6,
            ],
            [
                'id' => 107,
                'brewer' => "Beerland",
                'name' => "INVISIBLE ORANGES",
                'description' => "A dark, hoppy saision. Invisible Oranges will hit you with pronounced notes of dark chocolate and citrus fruit with being dry and balanced.",
                'style' => "IPA - Black",
                'abv' => 6.5,
                'complexity' => "EASY DRINKING",
                'section_id' => 6,
            ],
            [
                'id' => 108,
                'brewer' => "Rocky Ridge Brewing Co",
                'name' => "FROOTIE & THE BLOWFISH",
                'description' => "Yo, we heard you like big dumb sours...We've got you covered with this rambunctious triple fruited imperial sour. Packed full of enough fruit to keep you buzzin' for a hot minute, there's only one thing you can do, get a mouthful of froooot.",
                'style' => "Fruit Beer",
                'abv' => 8.0,
                'complexity' => "ADVENTUROUS",
                'section_id' => 6,
            ],
            ['id' => 109,    'brewer' => "Hiker Brewing Co",    'name' => "HOLD THE PORK",    'description' => "This amber rice lager is soured and infused with smoked pineapple and szechuan pepper to replicate everyone's favourite Chinese sauce.",    'style' => "Specialty Beer",    'abv' => 5.0,    'complexity' => "STEPPING UP",    'section_id' => 6,],
            ['id' => 110,    'brewer' => "One Drop Brewing Co",    'name' => "RASPBERRY LEMONADE",    'description' => "Wowzer! Fresh Aussie lemons and raspberries combine give a nostalgic-inducing, thirst-quenching, summer-making tasty wee number that'll have you dreaming of deep red sunsets of the Botany lagoon.",    'style' => "Specialty Brew",    'abv' => 6.2,    'complexity' => "STEPPING UP",    'section_id' => 6,],
            ['id' => 111,    'brewer' => "Rusty Penny Brewing",    'name' => "LUCKY CHARMS CEREAL MILK STOUT",    'description' => "Big Bold Thick and Sweet. The creation of our sales team led by Chris Sincek as he said 'going to the dark side' it boasts big rich stout flavour with thickness from the Oats in and sweetness from the marshmallow cereal. enjoy by the pint",    'style' => "Stout - Sweet Stout",    'abv' => 7.2,    'complexity' => "STEPPING UP",    'section_id' => 6,],
            ['id' => 112,    'brewer' => "Southern Highlands Brewing Co",    'name' => "RONIN - JAPANESE DOUBLE IPA",    'description' => "Blending rice and malted barley along side of Japanese bred Sorachi Ace used as a late addition and dry hop.",    'style' => "IPA - Double",    'abv' => 7.0,    'complexity' => "ADVENTUROUS",    'section_id' => 6,],
            [
                'id' => 113,
                'brewer' => "Roots & Leaves",
                'name' => "SPICY WOMBAT",
                'description' => "It's not commonly known, but the Spicy Wombat feasts on much more than just Roots and Leaves. He also devours spicy fire fruit chillies turned into Danger Dust and tempers it with limes for the ultimate in ginger beer flavours. This is a beer to cleanse your pallet and get a reset, or to use as the backbone for your fried snacks. You can womble like a wombat and have Roots and Leaves, or you can spice it up and try the Spicy Wombat to give so much more. Do you even dare bro?",
                'style' => "Ginger/Spiced Beer",
                'abv' => 6.0,
                'complexity' => "STEPPING UP",
                'section_id' => 6,
            ],
            [
                'id' => 114,
                'brewer' => "Funk Cider",
                'name' => "CHERRY NICE GRAF",
                'description' => "What could make a cider better...beer with cherries on top! Old Style Saison Graf (cider and beer) co-fermented with freshly juiced cherries Dry style with a hint of spice and cherry sweetness",
                'style' => "Graf (Cider/Beer blend)",
                'abv' => 7.5,
                'complexity' => "ADVENTUROUS",
                'section_id' => 6,
            ],
            [
                'id' => 115,
                'brewer' => "Hohly Water",
                'name' => "PINEAPPLE EXPRESS",
                'description' => "Delightful champagne notes combined with a burst of tropical fruit aromas. It has a rich, pillowy mouthfeel that is perfectly balanced with a mellow coconut flavor shining through.",
                'style' => "Seltzer",
                'abv' => 4.5,
                'complexity' => "EASY DRINKING",
                'section_id' => 6,
            ],
            [
                'id' => 116,
                'brewer' => "Felons Brewing Co",
                'name' => "BARREL AGED SELTZERITA",
                'description' => "Australian agave spirit barrel aged seltzer with lime and a hint of jalapeño. Having spent months in Australian agave spirit barrels, this super charged version of our fermented seltzer gains a smooth oaky character and a distinctive rich spirit note. Combined with lime zest and a dash of jalapeño, we’ve created an unconventional take on the classic margarita.",
                'style' => "Seltzer",
                'abv' => 13.0,
                'complexity' => "ADVENTUROUS",
                'section_id' => 6,
            ],
            [
                'id' => 117,
                'brewer' => "Cedar Creek Cider",
                'name' => "APPLE AND BLACK CURRANT CIDER",
                'description' => "This is our take on fresh new-world black currant and apple cider. It’s medium sweet with enough acidity to provide balance and a refreshing finish. The black currant is subtle, although present, with similarities to summer berries, cassis, and ripe dark cherries.",
                'style' => "Cider",
                'abv' => 4.5,
                'complexity' => "EASY DRINKING",
                'section_id' => 6,
            ],
            [
                'id' => 118,
                'brewer' => "Spreyton Cider Co",
                'name' => "SOUR PINEAPPLE CIDER",
                'description' => "Sour drops and Warheads! This will make your lips smack, we have combined our base apple cider with some seriously zingy pineapple juice - made down the road at our juicing operations. Apple-Pineapple sherbet, sour fizz.",
                'style' => "Cider",
                'abv' => 3.5,
                'complexity' => "EASY DRINKING",
                'section_id' => 6,
            ],
            [
                'id' => 119,
                'brewer' => "Eddies Cider",
                'name' => "EDDIES ORGANIC CIDER - CRISP APPLE",
                'description' => "Aromas of fresh organic apples with background hints of pineapple and citrus, the palate is well-balanced between acid and sweetness giving the apples full expression of their own character. The flavour is pleasingly appley with zesty freshness and mouth-filling roundness with a clean, lingering finish.",
                'style' => "Cider",
                'abv' => 4.5,
                'complexity' => "EASY DRINKING",
                'section_id' => 6,
            ],
            [
                'id' => 120,
                'brewer' => "Flying Brick Cider Co",
                'name' => "SPLICER",
                'description' => "A beverage salute to an iconic ice-cream. Cloudy blonde chartreuse in colour. Lashings of fresh Passionfruit, Pineapple & Lime curate a sublime fusion with the soft, creamy vanilla Pear Cider base. Refreshing tropical sweet fruit flavour balanced with naturally dryish zesty acid crunch.",
                'style' => "Cider",
                'abv' => 4.9,
                'complexity' => "EASY DRINKING",
                'section_id' => 6,
            ],
        ]);
    }
}
